name: openwisprflow
description: "Your voice everywhere - A minimalist voice-to-text application powered by Groq AI."


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.3.0
  cupertino_icons: ^1.0.8
  window_manager: ^0.3.8
  provider: ^6.1.1
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  flutter_sound: ^9.2.13
  path: ^1.9.0
  http: ^1.2.0
  http_parser: ^4.0.2
  system_tray: ^2.0.3
  hotkey_manager: ^0.1.8
  ffi: ^2.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/app_icon.ico
    - assets/app_icon.png

 